### ISSUE TITLE
v1.0b1 ROADMAP

### ISSUE THREAD

**Issue by Linuxoid85** [CalmiraLinux/cport#20]
- [ ] `install`, `remove`, `find`, `blacklist`, `info` subpacers (#13, etc.);
- [ ] [`cp_update` API Module;](#2)
- [ ] `find()` class in libcport;
- [ ] добавление/удаление портов в/из БД при установке/удалении;
- [ ] [проверка на наличие порта в БД при добавлении его в ЧС](#19)
- [ ] [Написание документации API](#8)
